<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="DTOs\CategoryDTOs\" />
    <Folder Include="DTOs\CartDTOs\" />
    <Folder Include="DTOs\OrderDTOs\" />
    <Folder Include="DTOs\ProductDTOs\" />
    <Folder Include="DTOs\UserDTOs\" />
    <Folder Include="Interfaces\Services\" />
    <Folder Include="Interfaces\Repository\" />
    <Folder Include="Mapper\" />
    <Folder Include="Services\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Mapster" Version="7.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

</Project>
